// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Qb3abo1oqPmfCLUeflp8JnOPlxoWja8',
    appId: '1:700180130860:web:1ed8c66b9a35f0c5b0f589',
    messagingSenderId: '700180130860',
    projectId: 'finalmobilecrossplatform',
    authDomain: 'finalmobilecrossplatform.firebaseapp.com',
    databaseURL: 'https://finalmobilecrossplatform-default-rtdb.firebaseio.com',
    storageBucket: 'finalmobilecrossplatform.appspot.com',
    measurementId: 'G-834B9WTRRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuf5jRtDOIIVwReVbGnoKUEycS1eyKMjo',
    appId: '1:700180130860:android:ff5f7daeac0ec727b0f589',
    messagingSenderId: '700180130860',
    projectId: 'finalmobilecrossplatform',
    databaseURL: 'https://finalmobilecrossplatform-default-rtdb.firebaseio.com',
    storageBucket: 'finalmobilecrossplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdTRSOnZCnHd1vBnbnB-LXJz4pFfQLWuw',
    appId: '1:700180130860:ios:6a012ad8c8b6282cb0f589',
    messagingSenderId: '700180130860',
    projectId: 'finalmobilecrossplatform',
    databaseURL: 'https://finalmobilecrossplatform-default-rtdb.firebaseio.com',
    storageBucket: 'finalmobilecrossplatform.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdTRSOnZCnHd1vBnbnB-LXJz4pFfQLWuw',
    appId: '1:700180130860:ios:6a012ad8c8b6282cb0f589',
    messagingSenderId: '700180130860',
    projectId: 'finalmobilecrossplatform',
    databaseURL: 'https://finalmobilecrossplatform-default-rtdb.firebaseio.com',
    storageBucket: 'finalmobilecrossplatform.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Qb3abo1oqPmfCLUeflp8JnOPlxoWja8',
    appId: '1:700180130860:web:bd3b2dfbd6b56637b0f589',
    messagingSenderId: '700180130860',
    projectId: 'finalmobilecrossplatform',
    authDomain: 'finalmobilecrossplatform.firebaseapp.com',
    databaseURL: 'https://finalmobilecrossplatform-default-rtdb.firebaseio.com',
    storageBucket: 'finalmobilecrossplatform.appspot.com',
    measurementId: 'G-JF4D48CJZ9',
  );
}
